services:
  backend:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./output:/app/output

  frontend:
    build: .
    command: streamlit run app.py
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./output:/app/output
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
