[theme]
primaryColor = "#4CAF50"             # Green color for buttons, accents
backgroundColor = "#FFFFFF"          # White background
secondaryBackgroundColor = "#f9f9f9" # Light gray background for sidebars
textColor = "#323db9"                # Dark gray text
font = "sans serif"                  # Available options: "sans serif", "serif", "monospace"
